apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  selector:
    matchLabels:
      app: registry
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: dockerhub/sunbird-rc-core
          env:
            - name: authentication_enabled
              value: "false"
            - name: connectionInfo_uri
              value: jdbc:postgresql://db:5432/registry
            - name: connectionInfo_username
              value: postgres
            - name: connectionInfo_password
              value: postgres
            - name: search_provider
              value: dev.sunbirdrc.registry.service.NativeSearchService
            - name: filestorage_connection_url
              value: http://file-storage.egov.svc.cluster.local:8080
            - name: filestorage_access_key
              value: "AKIA42DEGMQ2NZVNTLNI"
            - name: filestorage_secret_key
              value: "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"
            - name: filestorage_bucket_key
              value: issuance
            - name: sign_url
              value: http://certificate-signer:8079/sign
            - name: verify_url
              value: http://certificate-signer:8079/verify
            - name: signature_enabled
              value: "true"
            - name: pdf_url
              value: http://certificate-api:8078/api/v1/certificatePDF
            - name: template_base_url
              value: https://gist.githubusercontent.com/Sreejit-K/31d9dcd9585eced279ef417b84c0e2b4/raw/cee61226149ca8a6bd4996a95687102892f1bbc8/
            - name: template_folder_path 
              value: /home/sunbirdrc/config/public/_schemas/templates/
            - name: claims_url
              value: http://claim-ms:8082
          ports:
            - protocol: TCP
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 4
          volumeMounts:
            - name: schemas-volume
              mountPath: /home/sunbirdrc/config/public/_schemas/BirthCertificate.json 
              subPath: BirthCertificate.json 
            - name: schemas-template-volume
              mountPath: /home/sunbirdrc/config/public/_schemas/templates/BirthCertificate1.html 
              subPath: BirthCertificate1.html 
      volumes:
        - name: schemas-volume
          configMap:
            name: schema-config
        - name: schemas-template-volume
          configMap:
            name: schema-config-template
