apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-config
  namespace: demo-digit-sunbirdrc
data:
  BirthCertificate.json: |
    {
      "$schema": "http://json-schema.org/draft-07/schema",
      "type": "object",
      "properties": {
        "BirthCertificate1": {
          "$ref": "#/definitions/BirthCertificate1"
        }
      },
      "required": [
        "BirthCertificate1"
      ],
      "title": "BirthCertificate1",
      "definitions": {
        "BirthCertificate1": {
          "$id": "#/properties/BirthCertificate1",
          "type": "object",
          "title": "The BirthCertificate1 Schema",
          "required": [
            "name",
            "gender",
            "date_of_birth",
            "place_of_birth",
            "contact"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "gender": {
              "type": "string"
            },
            "date_of_birth": {
              "type": "string",
              "format": "date-time"
            },
            "hospital": {
              "type": "string"
            },
            "place_of_birth": {
              "type": "string",
              "enum": ["Bangalore", "Mysore", "Mandya"]
            },
            "name_of_mother": {
              "type": "string"
            },
            "name_of_father": {
              "type": "string"
            },
            "present_address": {
              "type": "string",
              "minLength": 10,
              "maxLength": 50
            },
            "contact": {
              "type": "string"
            }
          }
        }
      },
      "_osConfig": {
        "uniqueIndexFields": [
          "contact"
        ],
        "ownershipAttributes": [],
        "roles": [],
        "inviteRoles": [
          "anonymous"
        ],
        "credentialTemplate": {
          "@context": [
            "https://www.w3.org/2018/credentials/v1",
            {
              "@context": {
                "@version": 1.1,
                "@protected": true,
                "BirthCertificate1": {
                  "@id": "https://github.com/sunbird-specs/vc-specs#BirthCertificate1",
                  "@context": {
                    "id": "@id",
                    "@version": 1.1,
                    "@protected": true,
                    "skills": "schema:Text",
                    "name": "schema:Text",
                    "gender": "schema:Text",
                    "date_of_birth": "schema:Text",
                    "hospital": "schema:Text",
                    "place_of_birth": "schema:Text",
                    "name_of_mother": "schema:Text",
                    "name_of_father": "schema:Text",
                    "present_address": "schema:Text",
                    "contact": "schema:Text"
                  }
                }
              }
            }
          ],
          "type": [
            "VerifiableCredential"
          ],
          "issuanceDate": "2021-08-27T10:57:57.237Z",
          "credentialSubject": {
            "type": "BirthCertificate1",
            "name": "{{name}}",
            "gender": "{{gender}}",
            "date_of_birth": "{{date_of_birth}}",
            "hospital": "{{hospital}}",
            "place_of_birth": "{{place_of_birth}}",
            "name_of_mother": "{{name_of_mother}}",
            "name_of_father": "{{name_of_father}}",
            "present_address": "{{present_address}}",
            "contact": "{{contact}}"
          },
          "issuer": "did:web:sunbirdrc.dev/vc/BirthCertificate1"
        },
        "certificateTemplates": {
          "html": "https://gist.githubusercontent.com/tejash-jl/56b97ffcb99f93e2e1ec49e88c0c2c7f/raw/1242b9af7f58b9d5ca1e4f11d442aa4815598a31/BirthCertificate.html"
        }
      }
    }
